const {chromium}=require('/Users/hanafawy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const {journeys}=await import('file:///Users/hanafawy/Herd/vtravel-design/src/data/journeys.js');const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage();const errors=[],results=[],assets={};p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5175');
for(const width of [320,360,390,430,768,1024,1280,1440])for(const lang of ['en','ru','fr','de'])for(const theme of ['light','dark']){await p.setViewportSize({width,height:900});await p.evaluate(({lang,theme})=>{localStorage.setItem('thevtravel-language',lang);localStorage.setItem('thevtravel-theme',theme)},{lang,theme});
for(const route of ['/','/journeys','/contact','/about','/faq','/how-booking-works','/journeys/luxor-west-bank-at-dawn','/journeys/white-desert-adventure']){await p.goto('http://127.0.0.1:5175'+route,{waitUntil:'domcontentloaded'});await p.locator('h1').first().waitFor();assert.equal(await p.locator('.jd-not-found').count(),0,route);await p.evaluate(()=>document.fonts.ready);let check=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,font:getComputedStyle(document.body).fontFamily,ctas:[...document.querySelectorAll('a,button')].filter(e=>getComputedStyle(e).backgroundColor==='rgb(253, 85, 1)').map(e=>getComputedStyle(e).color)}));assert.equal(check.overflow,0,`${width} ${lang} ${theme} ${route}`);assert(check.font.includes('DM Sans'));assert(check.ctas.every(c=>c==='rgb(255, 255, 255)'));await p.evaluate(()=>scrollTo(0,600));assert(Math.abs(await p.locator('.site-header').evaluate(e=>e.getBoundingClientRect().top))<1,`sticky ${route}`);
if(route==='/journeys'){assert.equal(await p.locator('.view-controls').count(),width<768?0:1);const links=await p.locator('.listing-card').evaluateAll(cards=>cards.map(c=>[...c.querySelectorAll('a')].map(a=>a.getAttribute('href'))));assert(links.every(a=>a.length>=3&&a.every(h=>h===a[0]&&h.startsWith('/journeys/'))));}
if(width===1440&&lang==='en'){const images=await p.evaluate(()=>{const out=[];document.querySelectorAll('*').forEach(e=>{if(e.tagName==='IMG')out.push({src:e.getAttribute('src'),width:e.naturalWidth,height:e.naturalHeight});for(const pseudo of [null,'::before','::after']){const bg=getComputedStyle(e,pseudo).backgroundImage;for(const m of bg.matchAll(/url\(["']?([^"')]+)["']?\)/g))out.push({src:new URL(m[1],location.href).pathname})}});return out});for(const i of images){if(!i.src?.startsWith('/assets/'))continue;assets[i.src]??={pages:[],width:i.width,height:i.height};if(!assets[i.src].pages.includes(route))assets[i.src].pages.push(route)}}
results.push({width,lang,theme,route,...check});}
await p.locator('.language-trigger').click();assert.equal(await p.locator('[role=option]').count(),4);await p.keyboard.press('End');assert(await p.locator('[role=option]').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');assert.equal(await p.locator('[role=listbox]').count(),0);assert(await p.locator('.language-trigger').evaluate(e=>e===document.activeElement));}
fs.writeFileSync('.impeccable/refinement/latest-matrix.json',JSON.stringify({results,assets,errors},null,2));console.log('Matrix passed: '+results.length);const routes=[];for(const j of journeys){await p.goto('http://127.0.0.1:5175'+j.detailsHref,{waitUntil:'domcontentloaded'});await p.locator('h1').first().waitFor();assert.equal(await p.locator('h1').count(),1);assert(!await p.getByText('Journey not found',{exact:true}).count());routes.push({title:j.title,route:j.detailsHref,image:j.image});}
await p.setViewportSize({width:390,height:844});await p.goto('http://127.0.0.1:5175/journeys');await p.locator('.language-trigger').click();await p.locator('[role=option]').first().click();await p.locator('.menu-button').click();assert.equal(await p.locator('.mobile-nav .language-selector').count(),0);assert.equal(await p.locator('.mobile-nav a:not(.button) svg').count(),0);await p.screenshot({path:'.impeccable/refinement/latest-mobile-menu.png'});await p.keyboard.press('Escape');await p.locator('.language-trigger').click();await p.locator('[role=option]').nth(1).click();assert.equal((await p.locator('.language-trigger').innerText()).trim(),'RU');await p.locator('.language-trigger').click();await p.locator('h1').click();assert.equal(await p.locator('[role=listbox]').count(),0);
assert.equal(errors.length,0);fs.writeFileSync('.impeccable/refinement/latest-verification.json',JSON.stringify({results,routes,assets,errors},null,2));console.log(JSON.stringify({states:results.length,routes:routes.length,assets:Object.keys(assets).length,errors}));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
